# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Build with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Setup node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Build with Maven
      run: mvn install
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: target/cloudgene-installer.sh
